import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Rent Man",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="[background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)] min-h-screen">

      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      >
      <Navbar/>
      <div className="grid min-h-[calc(100vh-64px)] grid-rows-[1fr_auto]">

        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}

